### ISSUE TITLE
No option to keep floaterm open after task finishes

### ISSUE THREAD

**Issue by eulertour** [skywind3000/asyncrun.extra#2]
The floaterm runner that used to be listed at https://github.com/skywind3000/asyncrun.vim/wiki/Customize-Runner didn't terminate the process after the task was completed, which allowed for running other commands. Is it possible to add an option for the floaterm runner in this repo to do the same thing?

For reference, the old version of the runner is here:
```
function! s:runner_proc(opts)
  let curr_bufnr = floaterm#curr()
  if has_key(a:opts, 'silent') && a:opts.silent == 1
    FloatermHide!
  endif
  let cmd = 'cd ' . shellescape(getcwd())
  call floaterm#terminal#send(curr_bufnr, [cmd])
  call floaterm#terminal#send(curr_bufnr, [a:opts.cmd])
  stopinsert
  if &filetype == 'floaterm' && g:floaterm_autoinsert
    call floaterm#util#startinsert()
  endif
endfunction
let g:asyncrun_runner = get(g:, 'asyncrun_runner', {})
let g:asyncrun_runner.floaterm = function('s:runner_proc')
```

**Comment by skywind3000** [comment]
as your wish, new runner `floaterm_reuse` introduced in the latest version, 

try:

    :AsyncRun -mode=term -pos=floaterm_reuse  echo 1234

**Comment by eulertour** [comment]
Thanks!
